{"ast":null,"code":"import { catchError, throwError } from 'rxjs';\nimport * as i0 from \"@angular/core\";\nimport * as i1 from \"@angular/common/http\";\nclass LoginformService {\n  constructor(http) {\n    this.http = http;\n  }\n  login(credentials) {\n    return this.http.get('../../../asdsets/users.json').pipe(catchError(this.handleError));\n  }\n  //!vamo a utilizar un manejador de errores en funcion de las peticiones http\n  //!muchas veces la respuesta de la bd/api puede contener errores. Por ello se utiliza catchError\n  handleError(error) {\n    //veremos si esta mal formulado el request o el problema esta en el back\n    if (error.status == 0) {\n      console.log(\"se ha producido un error\" + error.error);\n    } else {\n      console.log(\"el backend retorno el codigo de estado\", error.status, error.error);\n    }\n    return throwError(() => new Error('Algo fallo, por favor intente nuevamente'));\n  }\n}\nLoginformService.ɵfac = function LoginformService_Factory(t) {\n  return new (t || LoginformService)(i0.ɵɵinject(i1.HttpClient));\n};\nLoginformService.ɵprov = /*@__PURE__*/i0.ɵɵdefineInjectable({\n  token: LoginformService,\n  factory: LoginformService.ɵfac,\n  providedIn: 'root'\n});\nexport { LoginformService };","map":{"version":3,"names":["catchError","throwError","LoginformService","constructor","http","login","credentials","get","pipe","handleError","error","status","console","log","Error","i0","ɵɵinject","i1","HttpClient","factory","ɵfac","providedIn"],"sources":["/home/sarja/Desktop/Tecnicatura/AS con Angular/ArSalud/ISPC-2023/FRONT/src/app/services/auth/loginform.service.ts"],"sourcesContent":["import { Injectable } from '@angular/core';\nimport { loguinRequest } from './loguinRequest';\nimport { Observable, catchError, throwError } from 'rxjs';\nimport { HttpClient, HttpErrorResponse } from '@angular/common/http';\nimport { User } from './user';\n\n@Injectable({\n  providedIn: 'root'\n})\nexport class LoginformService {\n\n  constructor( private http: HttpClient) {\n\n  }\n\n  login( credentials: loguinRequest ): Observable<User> {\n    return this.http.get<User>('../../../asdsets/users.json').pipe(catchError(this.handleError))\n  }\n\n  //!vamo a utilizar un manejador de errores en funcion de las peticiones http\n  //!muchas veces la respuesta de la bd/api puede contener errores. Por ello se utiliza catchError\n\n  private handleError(error: HttpErrorResponse){\n    //veremos si esta mal formulado el request o el problema esta en el back\n    if(error.status == 0){\n      console.log(\"se ha producido un error\" + error.error);\n    }else{\n      console.log(\"el backend retorno el codigo de estado\", error.status, error.error);\n    }\n    return throwError(()=> new Error('Algo fallo, por favor intente nuevamente'));\n  }\n}\n"],"mappings":"AAEA,SAAqBA,UAAU,EAAEC,UAAU,QAAQ,MAAM;;;AAIzD,MAGaC,gBAAgB;EAE3BC,YAAqBC,IAAgB;IAAhB,KAAAA,IAAI,GAAJA,IAAI;EAEzB;EAEAC,KAAKA,CAAEC,WAA0B;IAC/B,OAAO,IAAI,CAACF,IAAI,CAACG,GAAG,CAAO,6BAA6B,CAAC,CAACC,IAAI,CAACR,UAAU,CAAC,IAAI,CAACS,WAAW,CAAC,CAAC;EAC9F;EAEA;EACA;EAEQA,WAAWA,CAACC,KAAwB;IAC1C;IACA,IAAGA,KAAK,CAACC,MAAM,IAAI,CAAC,EAAC;MACnBC,OAAO,CAACC,GAAG,CAAC,0BAA0B,GAAGH,KAAK,CAACA,KAAK,CAAC;KACtD,MAAI;MACHE,OAAO,CAACC,GAAG,CAAC,wCAAwC,EAAEH,KAAK,CAACC,MAAM,EAAED,KAAK,CAACA,KAAK,CAAC;;IAElF,OAAOT,UAAU,CAAC,MAAK,IAAIa,KAAK,CAAC,0CAA0C,CAAC,CAAC;EAC/E;;AArBWZ,gBAAgB,C;mBAAhBA,gBAAgB,EAAAa,EAAA,CAAAC,QAAA,CAAAC,EAAA,CAAAC,UAAA;AAAA;AAAhBhB,gBAAgB,C;SAAhBA,gBAAgB;EAAAiB,OAAA,EAAhBjB,gBAAgB,CAAAkB,IAAA;EAAAC,UAAA,EAFf;AAAM;SAEPnB,gBAAgB"},"metadata":{},"sourceType":"module","externalDependencies":[]}